### ISSUE TITLE
How to build patchwork++ without using open3d？

### ISSUE THREAD

**Issue by YangkoC** [url-kaist/patchwork-plusplus#10]
It is too difficult to install open3d Library in Windows environment. I want to know how to build your algorithm without open3d! I hope you can help me, thank you!

**Comment by seungjae24** [comment]
Hi @YangkoC, which language will you use to operate Patchwork++? Python or C++?

**Comment by YangkoC** [comment]
python

**Comment by seungjae24** [comment]
I will open a branch, [10-how-to-build-patchwork++-without-using-open3d](https://github.com/url-kaist/patchwork-plusplus/tree/10-how-to-build-patchwork%2B%2B-without-using-open3d), for a week. It doesn't have any dependency on Open3D. Also, it only works on Python. But, you must be aware that you cannot visualize the ground segmentation result in this branch.

By the way, I suggest you try to install Open3D in Windows and build the version updated on the master. I find that Open3D supports Windows10 environment as written in [this link](http://www.open3d.org/docs/release/getting_started.html).

**Comment by YangkoC** [comment]
OK, thank you very much for your help! I will try to install Open3D again
