### ISSUE TITLE
ground segmentation issue with nonground points below ground plane

### ISSUE THREAD

**Issue by LidarPCL** [url-kaist/patchwork-plusplus#21]
Thanks for sharing your great work. It shows a wonderful performance in general utilization. However, I have been struggling with the high false positive and false negative rate when applying the algorithm in the scene where there are drainage ditches along the side of the road as the picture shown below. Since the algorithm selects the lowest height points as initials seeds, it easily takes the bottom of the drainage ditches as ground and the road next to the ditches as nonground. I tried to use smaller bins to help with this problem, but the running time goes up too much to meet the real time requirement when using bins with smaller size. I was wondering if you could provide any suggestions to cover this scenario. Any thoughts would be appreciated. 
![drainage-ditch](https://user-images.githubusercontent.com/101536471/233237616-1e4e21db-5da2-4792-8f93-55ae30cf4b85.jpg)

**Comment by seungjae24** [comment]
Hi @LidarPCL,

Thank you for employing our algorithm.

Well, it would be great if you share your own bag file to me by an e-mail written on README. I will check that it is possible to be solved easily or not. Thank you for figuring out which one causes this problem and trying several things. By the way, sorry for a late response. I was a little busy for few weeks..
