### ISSUE TITLE
When using 16-beam lidar, there will be false detection at close range

### ISSUE THREAD

**Issue by Kazawaryu** [url-kaist/patchwork-plusplus#29]
Thanks for your awsome work, it really helps me a lot.

But when I try to test custom data recorded by my 16-beam lidar, it happens in almost each point cloud, there will be false detection at close range, like this:
![image](https://github.com/url-kaist/patchwork-plusplus/assets/112942833/83230214-fe1b-4b92-9a67-2f9026d64e40)

I wonder if there is any way to solve this problem, or could you please tell me the reason? Thanks a lot.

**Comment by Kazawaryu** [comment]
@seungjae24

**Comment by seungjae24** [comment]
Hi @Kazawaryu , thank you for sharing your situation.

Could you please check the min distance in the patchworkpp:Params? The points near than the default min distance, which is 2.7m, would be segmented as non-ground points. If you still struggle with a problem, you can share your data file then it would be better for me to understand the situation precisely. You can send a data by e-mail, it's written on the readme.

Thank you :)

**Comment by Kazawaryu** [comment]
> Hi @Kazawaryu , thank you for sharing your situation.
> 
> Could you please check the min distance in the patchworkpp:Params? The points near than the default min distance, which is 2.7m, would be segmented as non-ground points. If you still struggle with a problem, you can share your data file then it would be better for me to understand the situation precisely. You can send a data by e-mail, it's written on the readme.
> 
> Thank you :)

Thank you for your help.

The data was recorded across in campus on a robot, there may be some problem using default parameters. I meticulously read your papers and change the parameters like you said, it works prefectly!

Thanks a lot for your help :)
