### ISSUE TITLE
How to refine the performance on my own dataset?

### ISSUE THREAD

**Issue by wcshen** [url-kaist/patchwork-plusplus#30]
Thanks for your great work and release the demo!
When i apply patchwork++ in my own data to segment ground_plane:
one obvious FP on the very flatten ground:
![image](https://github.com/url-kaist/patchwork-plusplus/assets/38600406/7604dee3-4359-4d99-a0b3-38fa816df8ab)

![image](https://github.com/url-kaist/patchwork-plusplus/assets/38600406/d3fd1f89-6c26-41a0-a412-7f264ccee678)

Also many ground-points on the obvious obstacles:
![image](https://github.com/url-kaist/patchwork-plusplus/assets/38600406/af876550-bf52-40b4-8157-ff98deb93d1e)

**Does it one exist problem of the pathwork++, or can i refine the performance by changing some params?**

**Comment by wcshen** [comment]
This is the pcd file:
https://drive.google.com/file/d/19QOYjPbPuY2lXBslSs9FzlWYXhyOXNYL/view?usp=sharing

**Comment by seungjae24** [comment]
Hi @wcshen, thank you for having interest on our work.

Patchwork++ was developed to be worked self-adaptively to reduce efforts for finding optimal parameters. However, of course, some unwanted result could be occured as you gave us. I don't think simply changing some parameters would lead a dramatic performance change in your case. Thank you.

**Comment by SuperCarryFu** [comment]
Hi! How can I modify the read_din function so that I can read the pcd file.
