### ISSUE TITLE
 I need to modify demo_visualize to read PCD files. How should I do it?

### ISSUE THREAD

**Issue by SuperCarryFu** [url-kaist/patchwork-plusplus#38]
![image](https://github.com/url-kaist/patchwork-plusplus/assets/83562877/93daa5ba-3e78-4396-98be-ace1a5d4e879)
![image](https://github.com/url-kaist/patchwork-plusplus/assets/83562877/c1c5b9c8-8824-425b-b381-d2c4181929bb)
For example, what should I do with these two types of PCD files?

**Comment by seungjae24** [comment]
Hi @SuperCarryFu,

Reading PCD files without PCL (Point Cloud Library) is not a common thing. But, in this package, we do not contain any PCL dependencies due some known issues related to the compatibility between pybind and PCL.

If you want to operate Patchwork++ with PCD file, it would be great to use PCL. You can find our another repository, [patchwork-plusplus-ros](https://github.com/url-kaist/patchwork-plusplus-ros), which is implemented with PCL. You can refer this one.

Also, I recommend you include x, y, z, intensity in point cloud data if you want to use Patchwork++ without any issue. If you want to operate Patchwork++ without intensity value, you may need to modify some parts of codes.

Thank you.
