### ISSUE TITLE
An error when build patchworkpp

### ISSUE THREAD

**Issue by tianchengdw** [url-kaist/patchwork-plusplus#4]
Hello, thank you for your nice work! I want to build patchworkpp with python. After 'cmake ..', when I performed 'make', an error occured as follows.  Could you help me fix it?
`
Scanning dependencies of target patchworkpp
[ 25%] Building CXX object patchworkpp/CMakeFiles/patchworkpp.dir/src/patchworkpp.cpp.o
In file included from /usr/include/eigen3/Eigen/Core:297:0,
                 from /usr/include/eigen3/Eigen/Dense:1,
                 from /data1/patchwork-plusplus/patchworkpp/include/patchworkpp.h:6,
                 from /data1/patchwork-plusplus/patchworkpp/src/patchworkpp.cpp:1:
/usr/include/eigen3/Eigen/src/Core/DenseCoeffsBase.h: In instantiation of ‘Eigen::DenseCoeffsBase<Derived, 0>::CoeffReturnType Eigen::DenseCoeffsBase<Derived, 0>::coeff(Eigen::Index) const [with Derived = Eigen::PartialReduxExpr<Eigen::Matrix<float, -1, 3>, Eigen::internal::member_mean<float>, 0>; Eigen::DenseCoeffsBase<Derived, 0>::CoeffReturnType = float; Eigen::Index = long int]’:
/usr/include/eigen3/Eigen/src/Core/DenseCoeffsBase.h:181:19:   required from ‘Eigen::DenseCoeffsBase<Derived, 0>::CoeffReturnType Eigen::DenseCoeffsBase<Derived, 0>::operator()(Eigen::Index) const [with Derived = Eigen::PartialReduxExpr<Eigen::Matrix<float, -1, 3>, Eigen::internal::member_mean<float>, 0>; Eigen::DenseCoeffsBase<Derived, 0>::CoeffReturnType = float; Eigen::Index = long int]’
/data1/patchwork-plusplus/patchworkpp/src/patchworkpp.cpp:61:48:   required from here
/usr/include/eigen3/Eigen/src/Core/DenseCoeffsBase.h:141:7: error: static assertion failed: THIS_COEFFICIENT_ACCESSOR_TAKING_ONE_ACCESS_IS_ONLY_FOR_EXPRESSIONS_ALLOWING_LINEAR_ACCESS
       EIGEN_STATIC_ASSERT(internal::evaluator<Derived>::Flags & LinearAccessBit,
       ^
patchworkpp/CMakeFiles/patchworkpp.dir/build.make:81: recipe for target 'patchworkpp/CMakeFiles/patchworkpp.dir/src/patchworkpp.cpp.o' failed
make[2]: *** [patchworkpp/CMakeFiles/patchworkpp.dir/src/patchworkpp.cpp.o] Error 1
CMakeFiles/Makefile2:152: recipe for target 'patchworkpp/CMakeFiles/patchworkpp.dir/all' failed
make[1]: *** [patchworkpp/CMakeFiles/patchworkpp.dir/all] Error 2
Makefile:148: recipe for target 'all' failed
make: *** [all] Error 2
`

**Comment by seungjae24** [comment]
Hello, thank you for having interest on our work!

Actually, I can't help you because I don't know how your environment is configured.

By the way, according to your error message, may be I can suggest you to find out the problem related to Eigen library. But, unfortunately, I don't know which is the exact problem of your situation.

If you find out why the error occurs and how to solve it, please re-open the issue and share the problem and solution for other users. Thank you :)
