### ISSUE TITLE
About ground plane

### ISSUE THREAD

**Issue by huixiancheng** [url-kaist/patchwork-plusplus#43]
Hi, Seungjae. I used the official [script](https://github.com/url-kaist/patchwork-plusplus/blob/master/examples/python/demo_visualize.py) to test Patchwork++ on example KITTI data and it performed well. I wanna know if Patch++ supports exporting ground plane equations that are similar to Ax + By + Cz + D = 0

**Comment by huixiancheng** [comment]
Also, I find that the method can not cover some case. As follow, some point that above ground been seg as groud. Any hy_params to adjust this?
![2023-12-08_17-12](https://github.com/url-kaist/patchwork-plusplus/assets/65054204/815121a6-26dc-4251-a1b6-de8d2306fc02)

**Comment by seungjae24** [comment]
Hi @huixiancheng,

> I wanna know if Patch++ supports exporting ground plane equations that are similar to Ax + By + Cz + D = 0

In the existing code, it doesn't have a function that exports ground plane equations. But, as Patchwork++ estimates the normal and mean of the ground points in each patch, you can get them easily.

> Any hy_params to adjust this?

Your given image is not enough for me to figure out which is the problem and how to solve it. Sorry :(

**Comment by huixiancheng** [comment]
thx for your reply.  solved.

**Comment by arun-venkat-23** [comment]
Hey @huixiancheng 

Could you please let me know on how you solved it. I am facing the same issue, there are points which are above the ground but are still categorized as ground.

**Comment by wanglaotou** [comment]
> Hey @huixiancheng
> 
> Could you please let me know on how you solved it. I am facing the same issue, there are points which are above the ground but are still categorized as ground.

same issue, have you solved the problem, thanks.
