### ISSUE TITLE
codes question

### ISSUE THREAD

**Issue by wcyjerry** [url-kaist/patchwork-plusplus#46]
Hi, I just want to know that :
in PatchWorkpp::estimateGround, Why is  update_elevation_thr and update_flatness_thr is in the end, it seems take no effect ?

**Comment by seungjae24** [comment]
Hi @wcyjerry!

The two functions you mentioned are designed for updating the threshold values for further estimation. If you uses Patchwork++ to sequential point cloud data, it would take effect. Thank you :)
