### ISSUE TITLE
Installing without sudo

### ISSUE THREAD

**Issue by YishGene** [url-kaist/patchwork-plusplus#47]
Hi, I'm very much interested in your project, and trying to build your repo's wheel so I can try it out for myself. However, the build script is heavily dependent on root privileges/sudo. Do you have a method for building without these requirements and/or prebuilt wheels that you can share?

**Comment by seungjae24** [comment]
Hi @YishGene,

Honestly, I didn't get your situtation. Could you please let me know details of your problem or sth you need?
By the way, we've tested our algorithm primarily on Ubuntu. Therefore, if you are using another environment it might be hard to get our help.

**Comment by YishGene** [comment]
Thanks for replying @seungjae24, the problem is that I'm working on a system where I don't have root privileges, so I can't run commands like sudo apt-get install.

In the meantime I created a solution by building in a docker container where I have the privileges. There are a few more steps involved, if you like I can MR. 

Everything is done in Ubuntu.

**Comment by seungjae24** [comment]
I see, it sounds great that you've already solved the problem by using docker container.

We're always open to get contributions. You are free to create a pull request on our repository. If you can provide the Dockerfile to create the image, properly working with Patchwork++, I would like to appreciate you.

Thank you :)
