### ISSUE TITLE
Regarding varying mean sensor height

### ISSUE THREAD

**Issue by arun-venkat-23** [url-kaist/patchwork-plusplus#51]
Hey @seungjae24 

While calculating the initial_seeds, I was wondering why does the mean height of points vary a lot. My sensor is mounted at around 1.7m from the ground but the mean height of points does go till 3.4m

**Comment by LimHyungTae** [comment]
How come??? Could you see the example please?

**Comment by arun-venkat-23** [comment]
Since the plane fitting is done bin-wise, there are a few bins in which the mean height of points are at around ~3.4 (trees). Due the absence of ground points in the particular region, the algorithm during the initial seeds computation takes the mean height and tags all points below the mean as ground. This is an issue, do you think there is a workaround for this?

**Comment by LimHyungTae** [comment]
Then how about just applying the global z threshold before taking the point cloud as input? The points under the tree seem definite false positives, which can be easily filtered out.

**Comment by arun-venkat-23** [comment]
This might work for a flat/planar ground surface. In case of slopes, this might start putting out issues
