### ISSUE TITLE
Code release under MIT or BSD or Apache license? 

### ISSUE THREAD

**Issue by anuraj-rp** [url-kaist/patchwork-plusplus#56]
Hi,

Is there any plan to release the source code under MIT/BSD/Apache licenses? 

Br
Anuraj

**Comment by LimHyungTae** [comment]
Hello, @anuraj-rp thanks for your interest. Unfortunately, we don't know our PI's criteria. Maybe it would be better to send an e-mail to our advisor if you need this code for your business.

**Comment by anuraj-rp** [comment]
Hi,

Not needed for business. Just that it is more common now to make open source releases under MIT/BSD/Apache and hence asked the question

Thank you
