### ISSUE TITLE
About the parameters in different environments

### ISSUE THREAD

**Issue by moonsheep99** [url-kaist/patchwork-plusplus#61]
Hello! Thanks for this great work!
I'm trying to use it for ground segmentation of point clouds in an indoor environment, which is relatively narrow.
I have adjusted some parameters, but the segmentation is not as accurate as it is outside. There are many error points that are segmented as ground points, including ceilings, objects on the ground, and a few vertical walls. Would you give some suggestions on parameter adjustment？
The picture is as follows (The red points are the ground points segmented by patchwork++): 
![csq4cjjdqn3eevpg74ig](https://github.com/user-attachments/assets/5182fedd-40df-44e9-8962-e8a62b19b355)
![csq4cct9roqhrfvqs3bg](https://github.com/user-attachments/assets/ded7a298-4091-408b-a007-12ef62d42de9)
![csq4c5od4n1u260a4f8g](https://github.com/user-attachments/assets/6f0f4f5b-724f-4116-b80c-7bab0fe8d977)

**Comment by LimHyungTae** [comment]
I guess ground segmentation failed. Could you give me some pcd files?

**Comment by moonsheep99** [comment]
Hello, thanks for your reply, I embedded patchwork++ into SLAM, this is a .pcd file of the mapping results (10Hz point cloud measurements) for 20 seconds (I do ground segmentation of each frame of point clouds).
[scans.zip](https://github.com/user-attachments/files/18058802/scans.zip)

**Comment by LimHyungTae** [comment]
That's weird. In Patchwork++, 
1) it assumes that LiDAR coordinates should be front-left-up coordinates
2) Is your system handheld?
3) Which parameters did you change? Segmenting ceilings and tripods does not make sense.

**Comment by moonsheep99** [comment]
In fact, the data used comes from the dataset (this is in the initial phase, so the nearby ground is blind for LiDAR), but I will soon conduct real-world testing, I will follow your advice and make the sensor detect more ground points. 
By the way, do you think that the few number of ground points is what caused the poor segmentation result? Does the parameter file need to be modified? 
Thank you for your reply !

**Comment by LimHyungTae** [comment]
It might be. Going to the your problem back, I don't think ground segmentation is needed in your case since in that case, ground points are not dominant, aren't they?

**Comment by moonsheep99** [comment]
Thanks for your response. Indeed, there are few ground points in this scenario, but they are still important to me. I will adjust the LiDAR FoV to observe more ground points, and thank you again for your help!
