### ISSUE TITLE
About line_variable condition in TGR function

### ISSUE THREAD

**Issue by Acuno41** [url-kaist/patchwork-plusplus#7]
Hi. I'am little bit confused about TGR function's condition.

https://github.com/url-kaist/patchwork-plusplus/blob/0d430884cbea4c3cfa009cf99a46c4f04ae964e2/patchworkpp/src/patchworkpp.cpp#L417

The value 8 shouldn't it be adjustable for different sector sizes and environment ? 

Best regards.

**Comment by seungjae24** [comment]
Hi, thank you for the question!

Your point makes sense. It would be better if the threshold of `line_variable` is varied with respect to different sector sizes.
