### ISSUE TITLE
would you provide the metrics? 

### ISSUE THREAD

**Issue by dhotdog** [url-kaist/patchwork-plusplus#9]
Thank you in advance for making your impressive work available to the public. The strategy of patchwork partitioning is a brilliant idea.  We'd like to cite your paper in our work.

While reading your code, I didn't find **the metrics for accuracy, recall, F1** calculation. Would you kindly provide your code for these calculation?

**Comment by seungjae24** [comment]
Thank you for having interest on our work.

If you want to try the evaluation code, you can visit the [Ground Segmentation Benchmark](https://github.com/url-kaist/Ground-Segmentation-Benchmark) repository from url-kaist.
In this repository, you can find evaluation metrics and calculation codes based on SemanticKITTI dataset.

Thank you :)
